version: '3'

volumes:
  db:
    driver: local
services:
  server:
    build: ./container/Dockerfile.backend
    env_file:
      - .tg-token
    restart: always
    links:
      - "db"
    depends_on:
      - db
  db:
    image: mongo:4.4
    mem_limit: 512M
    cpu_percent: 60
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fworootpassword
    volumes:
    - db:/data/db