import { ItemComponent, type AchievementDefinition } from '@fwo/shared';

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  // --- Боевые (Combat) ---
  {
    id: 'arena_wins_10',
    title: 'Первые триумфы',
    description: 'Одержите 10 побед на Арене',
    category: 'combat',
    stat: 'wins',
    goal: 10,
    reward: { exp: 300, gold: 50, titleReward: 'Гладиатор' },
    icon: '⚔️',
  },
  {
    id: 'arena_wins_50',
    title: 'Закалённый боец',
    description: 'Одержите 50 побед на Арене',
    category: 'combat',
    stat: 'wins',
    goal: 50,
    reward: { exp: 1500, gold: 250, titleReward: 'Чемпион' },
    icon: '🏆',
  },
  {
    id: 'arena_wins_200',
    title: 'Легенда Арены',
    description: 'Одержите 200 побед на Арене',
    category: 'combat',
    stat: 'wins',
    goal: 200,
    reward: { exp: 6000, gold: 1000, components: { [ItemComponent.Steel]: 5 }, titleReward: 'Легенда Арены' },
    icon: '👑',
  },
  {
    id: 'damage_10k',
    title: 'Сокрушительный удар',
    description: 'Нанесите 10 000 суммарного урона в боях',
    category: 'combat',
    stat: 'damage',
    goal: 10000,
    reward: { exp: 500, gold: 100, titleReward: 'Разрушитель' },
    icon: '💥',
  },
  {
    id: 'damage_100k',
    title: 'Сила стихии',
    description: 'Нанесите 100 000 суммарного урона в боях',
    category: 'combat',
    stat: 'damage',
    goal: 100000,
    reward: { exp: 3000, gold: 500, components: { [ItemComponent.Arcanite]: 2 }, titleReward: 'Опустошитель' },
    icon: '⚡',
  },
  {
    id: 'kills_25',
    title: 'Жнец душ',
    description: 'Совершите 25 добиваний врагов',
    category: 'combat',
    stat: 'kills',
    goal: 25,
    reward: { exp: 800, gold: 150, titleReward: 'Палач' },
    icon: '💀',
  },
  {
    id: 'heal_10k',
    title: 'Дар милосердия',
    description: 'Восстановите 10 000 здоровья себе или союзникам',
    category: 'combat',
    stat: 'heal',
    goal: 10000,
    reward: { exp: 800, gold: 150, titleReward: 'Целитель' },
    icon: '💚',
  },

  // --- Исследования (Exploration) ---
  {
    id: 'forest_events_20',
    title: 'Тропа исследователя',
    description: 'Завершите 20 событий в Лесу',
    category: 'exploration',
    stat: 'forestEvents',
    goal: 20,
    reward: { exp: 400, gold: 80, components: { [ItemComponent.Wood]: 5 }, titleReward: 'Следопыт' },
    icon: '🌲',
  },
  {
    id: 'forest_events_100',
    title: 'Хозяин чащи',
    description: 'Завершите 100 событий в Лесу',
    category: 'exploration',
    stat: 'forestEvents',
    goal: 100,
    reward: { exp: 2500, gold: 500, components: { [ItemComponent.Leather]: 5 }, titleReward: 'Лесник' },
    icon: '🏕️',
  },

  // --- Башня (Tower) ---
  {
    id: 'tower_floors_5',
    title: 'Первые этажи',
    description: 'Пройдите 5 этажей Башни',
    category: 'tower',
    stat: 'towerFloors',
    goal: 5,
    reward: { exp: 500, gold: 100, titleReward: 'Восходитель' },
    icon: '🗼',
  },
  {
    id: 'tower_floors_20',
    title: 'Владыка высот',
    description: 'Пройдите 20 этажей Башни',
    category: 'tower',
    stat: 'towerFloors',
    goal: 20,
    reward: { exp: 3000, gold: 600, components: { [ItemComponent.Arcanite]: 3 }, titleReward: 'Хранитель Башни' },
    icon: '🏰',
  },

  // --- Крафт и Экономика (Craft) ---
  {
    id: 'items_crafted_5',
    title: 'Ученик кузнеца',
    description: 'Выкуйте 5 предметов в Кузне',
    category: 'craft',
    stat: 'itemsCrafted',
    goal: 5,
    reward: { exp: 300, gold: 100, components: { [ItemComponent.Iron]: 3 }, titleReward: 'Подмастерье' },
    icon: '🔨',
  },
  {
    id: 'items_crafted_20',
    title: 'Мастер Наковальни',
    description: 'Выкуйте 20 предметов в Кузне',
    category: 'craft',
    stat: 'itemsCrafted',
    goal: 20,
    reward: { exp: 2000, gold: 500, components: { [ItemComponent.Steel]: 5 }, titleReward: 'Мастер Кузни' },
    icon: '🛠️',
  },

  // --- Боссы (Boss) ---
  {
    id: 'boss_damage_50k',
    title: 'Вызов гиганту',
    description: 'Нанесите 50 000 суммарного урона Мировому Боссу',
    category: 'boss',
    stat: 'bossDamage',
    goal: 50000,
    reward: { exp: 2000, gold: 500, titleReward: 'Охотник на Титанов' },
    icon: '🐉',
  },
  {
    id: 'boss_damage_500k',
    title: 'Гроза исполинов',
    description: 'Нанесите 500 000 суммарного урона Мировому Боссу',
    category: 'boss',
    stat: 'bossDamage',
    goal: 500000,
    reward: { exp: 10000, gold: 2500, components: { [ItemComponent.Arcanite]: 10 }, titleReward: 'Убийца Богов' },
    icon: '⚡',
  },

  // --- Мастерство (Mastery) ---
  {
    id: 'reach_lvl_5',
    title: 'Путь воина',
    description: 'Достигните 5 уровня персонажа',
    category: 'mastery',
    stat: 'lvl',
    goal: 5,
    reward: { gold: 200, titleReward: 'Адепт' },
    icon: '⭐',
  },
  {
    id: 'reach_lvl_10',
    title: 'Ветеран боёв',
    description: 'Достигните 10 уровня персонажа',
    category: 'mastery',
    stat: 'lvl',
    goal: 10,
    reward: { gold: 1000, components: { [ItemComponent.Steel]: 2 }, titleReward: 'Ветеран' },
    icon: '🌟',
  },
];
