name: main

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  buildAndLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: bun install
        run: bun install
      - name: eslint
        run: bun run lint
  testContainerFrontend:
    environment: test
    needs: buildAndLint
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: catHD
          password: ${{ secrets.ghcr_token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: conteiners
          file: Dockerfile.frontend
          tags: |
            ghcr.io/cathd/fwo-ui-test:latest
  testContainerBackend:
    environment: test
    needs: buildAndLint
    if: github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: catHD
          password: ${{ secrets.ghcr_token }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: conteiners
          file: Dockerfile.backend
          tags: |
            ghcr.io/cathd/fwo-backend-test:latest